console.log("fuck up")
console.log("bc muje mat dkeh")

// if try fails then catch will print and always write the catch statement error proff
try {
    let a;
    console.log(a.length);
    console.log("hi there from inside")
} catch (error) {
    console.log("inside catch statement");
}

console.log("hi there")